#!/bin/bash
echo "Dropping all DBs"

for i in $(mysql -u root -e "show databases" -E --skip-column-names | grep -v ^* | grep -v ^information_schema | grep -v ^performance_schema | grep -v ^mysql); do
	mysql -u root -e "drop database ${i}"
	mysql -u root -e "flush privileges"
done

echo "All dropped"
